#!/bin/bash -xe
build/build-linux
scp target/x86_64-unknown-linux-gnu/release/edifm edifm@edifm.org:app/edifm+
ssh edifm@edifm.org '
    set -xe
    mv app/edifm+ app/edifm
    cd edifm
    git fetch origin master
    git reset --hard origin/master
    cd web
    bundle --path vendor/gems
'
ssh root@edifm.org systemctl restart edifm-web
